### ISSUE TITLE
Hope qmgo adds bulk batch processing

### ISSUE THREAD

**Issue by echoiron** [qiniu/qmgo#50] opened 2020-08-14 03:50 UTC
![image](https://user-images.githubusercontent.com/52339367/90211804-52f1f900-de24-11ea-884a-77a4d508e014.png)

**Comment by jiangz222** [comment] 2020-08-14 05:29
Bulk() is a  experimental in `mgo`, we will consider it ,thanks!

**Comment by jiangz222** [comment] 2020-08-14 06:28
welcome to wechat group

![avatar](http://pgo8q04yu.bkt.clouddn.com/qmgoG)

**Comment by xen0n** [comment] 2020-11-27 09:54
I think this is dupe of #98?

**Comment by jiangz222** [comment] 2021-01-16 04:57
Fixed by #153 #151

**Closed by jiangz222** 2021-01-16 04:57 UTC
Labels: duplicate, proposal
